services:
    reservations:
        build:
            context: .
            dockerfile: ./apps/reservations/Dockerfile
            target: development
        command: npm run start:dev reservations
        ports:
            - "3000:3000"
        volumes:
            - .:/urs/src/app